### ISSUE TITLE
Support bitstring, not only atoms

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [weareyipyip/Phoenix-API-Toolkit#40]
In Phoenix API the key is not an atom but a key.
So the generated macro don't matches correctly.

I suppose replacing every atoms to string is a good point.

**Comment by juulSme** [comment]
Hi Marc-Antione, support for string keys will be added in #34. We are still testing this code, and it will contain breaking changes leading to a major version bump (1.x.x). So I'm closing your issue for now, but know that this support is coming. 

And apologies for the delayed response, turns out I didn't have notifications enabled (I do now :smile:)

**Comment by juulSme** [comment]
On a sidenote; the reason we use atom keys is that we always pipe request parameters through an Ecto changeset (which converts the keys in the schema to atoms). You can do that as well, and gain better errors from your API as a bonus! Take a look at  https://hexdocs.pm/phoenix_api_toolkit/PhoenixApiToolkit.GenericRequestValidator.html
