### ISSUE TITLE
Pagination and total number of items

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [weareyipyip/Phoenix-API-Toolkit#42]
We are using the library with the latest version (1.0.0).
Excellent work ;-) 

We just figured an issue to retrieve the total number of element using the pagination.

Do you think it can be handle in the library ?
Thank you,
Marc-Antoine

**Comment by juulSme** [comment]
Hi, glad you like the lib! And thanks for providing feedback :) That's an issue that often returns in our own projects as well. Usually we choose not to show that info. As far as we know, there's no way (in Postgres) to retrieve the count without running the entire query again. 

So you could do something like this:

```elixir
@pagination %{atom_keys: true, limit: true, offset: true}

def list_with_count(filters \\ %{}) do
  {pagination_filters, filters} = Map.split(filters, [:limit, :offset])
  
  my_query =
    from(user in "users", as: :user)
    |> apply_filters(filters, fn
      filter, query -> standard_filters(query, filter, :user, @filter_definitions, &resolve_binding/2)
    end)
  
  count = my_query |> select([user: user], count(user.id)) |> Repo.one()
  results = my_query |> apply_filters(pagination_filters, &(standard_filters(&2, &1, :user, @pagination))) |> Repo.all()
  
  {results, count}
end
```

This somewhat clashes with the library's intent to resolve everything in a single query. You could still do it in a single round-trip to the database, by joining the two queries on `true`, but as far as I know that is as good as it's going to get.

We don't plan to solve this in the library because we want the lib to remain generically applicable and I don't really see how to solve the issue in a generic way (but we're open to suggestions!).

**Comment by juulSme** [comment]
Also, Postgres' `count()` function is quite slow because it has to do a seq scan of the query results. If you have a large table and no filters active, it will go through the entire table every time, so tread carefully.

**Comment by MarcAntoine-Arnaud** [comment]
Cool, thank you @juulSme,

We will test that today and if we have some issue(s) will will open new ones ;-)
