### ISSUE TITLE
Order by with string, not atom

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [weareyipyip/Phoenix-API-Toolkit#43]
Regarding the current API, it's only possible to use atom to order.
Is it possible to take in account string too as API generate string and not atom.

Thank you !

**Comment by juulSme** [comment]
I'm afraid that's not possible because Ecto only accepts atoms as the value of `order_by` (see https://hexdocs.pm/ecto/Ecto.Query.html#order_by/3).

This has been documented, although this could have been made clearer somewhere else: https://hexdocs.pm/phoenix_api_toolkit/PhoenixApiToolkit.Ecto.DynamicFilters.html#module-order-by-sorting

So in order to support strings as values, you would have to do something like this:
```elixir
defp atomify_order_by(%{"order_by" => order_by} = filters) do
  %{filters | "order_by" => String.to_existing_atom(order_by)}
end

defp atomify_order_by(filters), do: filters
```

Alternatively, and what we do ourselves, you can validate request query parameters in your endpoints using Ecto changesets, where the keys are cast to atoms for you. This has the huge benefit of generating clear 400 errors with error messages for your user, simply by having the invalid changesets fall through to a fallback controller that renders them. You can see an example here: https://hexdocs.pm/phoenix_api_toolkit/PhoenixApiToolkit.GenericRequestValidator.html#content

You can combine this with our special validator for `order_by`: https://hexdocs.pm/phoenix_api_toolkit/PhoenixApiToolkit.Ecto.Validators.html#validate_order_by/2

**Comment by MarcAntoine-Arnaud** [comment]
Yes cool !!
Thank you for this solution, it seams perfect.
We will come back if we found other issues related.

Best,
Marc-Antoine
